-- CREATE TABLE users(
--     id INTEGER(255) NOT NULL AUTO_INCREMENT,
--     -- fname VARCHAR(30) NOT NULL,
--     -- lname VARCHAR(30) NOT NULL,
--     username VARCHAR(20) NOT NULL,
--     pword VARCHAR(20) NOT NULL,
--     outdoors BOOLEAN NOT NULL,
--     nature BOOLEAN NOT NULL,
--     histSites BOOLEAN NOT NULL,
--     food BOOLEAN NOT NULL,
--     museums BOOLEAN NOT NULL,
--     fineArts BOOLEAN NOT NULL,
--     music BOOLEAN NOT NULL,
--     festivals BOOLEAN NOT NULL,
--     nightlife BOOLEAN NOT NULL,
--     locals BOOLEAN NOT NULL
--     primary key(id)
-- );
-- INSERT INTO user(username, pword, outdoors, nature, histSites, food, museums, fineArts, music, festivals, nightlife, locals)
-- VALUES("fname0123", "password0123", true, false, true, true, false, false, true, true, true, false);