module.exports = function(sequelize, DataTypes) {
    const Post = sequelize.define("Post", {
      country: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "US",
        validate: {
          len: [1]
        }
      },
      city: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "New York",
        validate: {
          len: [1]
        }
      },
      startMonth: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "01",
        validate: {
          len: [1]
        }
      },
      startDay: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "01",
        validate: {
          len: [1]
        }
      },
      startYear: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "19",
        validate: {
          len: [1]
        }
      },
      endMonth: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "01",
        validate: {
          len: [1]
        }
      },
      endDay: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "01",
        validate: {
          len: [1]
        }
      },
      endYear: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "19",
        validate: {
          len: [1]
        }
      },
      creator: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: "Autogenerated"
      },
      costMin: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: "0",
        validate: {
          len: [1]
        }
      },
      costMax: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: "0",
        validate: {
          len: [1]
        }
      }

    });
  
    // Post.associate = function(models) {
    //   // A Post should belong to an Author
    //   // A Post can't be created without an Author due to the foreign key constraint
    //   Post.belongsTo(models.User, {
    //     foreignKey: {
    //       allowNull: false
    //     }
    //   });
    // };

    return Post;
  };
  